#hello: Welcome to SOPS! Edit this file as you please!
#example_key: example_value
# Example comment
#example_array:
#    - example_value1
#    - example_value2
#example_number: 1234.56789
#example_booleans:
#    - true
#    - false
apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:sm26CqdDKaJ/N12N5thzhIjmlVWlsVqUqtxnRNJC96lHrHKRdQHiyydLHYkftDX2y+ICBHdikSpF68jkSJMj9ZhDvEbU6YC6N/uimkBPMXFkLMMfho5+Uly4Wq25pZ3hFNG6IqSdnIDmvSXHe317vFmSKC3KQHqMh77cOdp1u8AUDxfQWe7Ea8/MzVOgQARlCTf3yAXU/45auw==,iv:ONX0OH9sbxCYrYRGeVh/45dnwyN/I80e5JyfcGIO8oo=,tag:WTM8vpYp2DBgETHyS5NZjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-09T22:09:32Z"
    mac: ENC[AES256_GCM,data:ACaa0zn8Enf4gqybK/9xgEbxmr1AXurbH00CTfqH0zNYdxUI+w5P8IIamjJaosV3yAql2vKQcq0/NQ+yLtO7KwXZDeMg6pB+uO2Tmb4ZzUTTGYLtUKRhuc8vZJxC2lIv87i1LYWPtDD4VkTkNZA4dwA2V2liEGTAnEfKMGuQaJw=,iv:/vNidgJNSYMRLOrcrWYA86oHkx5Mo1BeTYL7DzOPHjA=,tag:qL9Va3YObXXXOJJVTghMnw==,type:str]
    pgp:
        - created_at: "2022-03-09T22:02:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9De2GFAylWNAQ//UyCtQQEdlvBSj7vJBBUnA9HbGvxIJ4QRxmk1X39qUKXt
            RHgbaZhg7gsl5wA78kNEPztZT3VDgG+DxJpoYd01eM3U3oRlGFl7FprUfea3tJ15
            Wx5kKJg9JkJpLM0FhtYrKKhaLNvrp1sFuD9a3eIXd03fCMLhQcKESspl8qTi0/Ba
            UmneVx8dNaEnuIaLJHKr6DLXWEinrH5OLhslpDG7TyZNMSw3bwJn8y9HiGFNGaWK
            HL4JXyU8L5Uou5CiappulS+aC3EUqeFGzK/oBfqVxtdmMxkf4UMRn1316IuzaC4O
            5v48KFozAklZK1dgWokyy30uORc9bthrVt933+nzjbFl5SeokfGpRHPgsCIb4KOB
            1p4ZXUqh5VHYcBRaYW52MURdh3L8V51lLxehIrXF1EaDwOoMguDfViNIW5Yj/dQm
            9M5NGpByt9zQZnxxrC8jBs7cAOQUEsI3Jew28n2VzOMOGt2Rgzh9MObCVUJbDjMY
            flvFbNvuUN6XbuDAe+YiZxYJ+fRUMdz71iU0OlumNo4S2saCZ32j4WeaV2gJUzus
            R09ubAwG2Mi5QsyBM8F2plUxN9WEg4o4xnZ4209xBJ2j6tSxl/6UVGTVrm7EpktZ
            GhXLV8VLGQTM2jJjERBgiGlKAZX9hbbf1Kl5xd00/PyzUYjV3sXFDeDAl29/qJDU
            aAEJAhDsciekIzV47i2KfaQq0vqaaBv67t038wklq7DCpQlPCeCVp3Tkv6rmKmg9
            4OlaBCjcbaqkyQIC7HxQucAFm2D3EVUWtyQdTiqF2Of6Dp6Dign+/RM8rCotjkjM
            aib9engRD7Pp
            =vDhx
            -----END PGP MESSAGE-----
          fp: 2ED44BA25B61DE7E4C3C8FDD4D73DB8D6EABCE8D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
